# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22240da265c56a94b5ab9d50862b5f56188dcc68e67d92b5a2da8789d931545ae0cdba115b0ec52466b037d17e97418c3446f34eb1c356ed714c79828b141578

test:
  secret_key_base: c1bfe22569cf1be9b0b513fe8d4b54cda1325820a3a9cda26cdd7294c0ac934fde0919e968227c0dcacf7024b6aa14050f30013bb0a6fa33b8735a1b945deac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
